#!/bin/bash

# PARAMS=""

#while (( "$#" )); do
#  case "$1" in
#    -f|--flag-with-argument)
#      FARG=$2
#      shift 2
#      ;;
#    --) # end argument parsing
#      shift
#      break
#      ;;
#    -*|--*=) # unsupported flags
#      echo "Error: Unsupported flag $1" >&2
#      exit 1
#      ;;
#    *) # preserve positional arguments
#      PARAMS="$PARAMS $1"
#      shift
#      ;;
#  esac
#done

# set positional arguments in their proper place
#eval set -- "$PARAMS"

if [[ $# -ne 1 ]]; then
  echo "Usage: sum_to_mono filename.wav"
else
  file_dir=`dirname $1`
  file_name=`basename -s .wav $1`
  chan_info=`probe_channels $1`
  if [[ $chan_info -ne 1 ]]; then
    [ -d "${file_dir}/originals" ] || mkdir "${file_dir}/originals"
    mv $1 "${file_dir}/originals/${file_name}.wav"
    ffmpeg -y -hide_banner -v quiet -i "${file_dir}/originals/${file_name}.wav" -ac 1 $1
  fi
fi
